/* Flobro website scripts. English lives inline in the HTML; other languages
 * are pre-rendered static pages generated from the JSON in /i18n. */
'use strict';

/* ----------------------------- language ------------------------------- */
/* Each language is a static page (/, /nl/, /es/, ...) generated by
 * scripts/generate-locale-pages.mjs. The select only navigates. */
var LANG_KEY = 'flobro-lang';
var LANGS = ['en', 'nl', 'es', 'de', 'fr', 'pt-br'];
var isWin = /win/i.test(
  (navigator.userAgentData && navigator.userAgentData.platform) || navigator.platform || '',
);

function detectLang() {
  var tag = (navigator.language || 'en').toLowerCase();
  if (tag.indexOf('pt') === 0) return 'pt-br';
  var short = tag.slice(0, 2);
  return LANGS.indexOf(short) > 0 ? short : 'en';
}

(function initLang() {
  var parts = location.pathname.split('/').filter(Boolean);
  var current = LANGS.indexOf(parts[0]) > 0 ? parts[0] : 'en';
  var page = parts[parts.length - 1];
  if (!page || LANGS.indexOf(page) !== -1) page = '';

  /* First visit: remember the browser language (or the page the visitor
   * landed on). An explicit pick in the select always wins afterwards. */
  var stored = localStorage.getItem(LANG_KEY);
  if (!stored) {
    stored = current !== 'en' ? current : detectLang();
    localStorage.setItem(LANG_KEY, stored);
  }
  /* Send visitors on an English page to their own language, like the old
   * runtime switcher did. Search engines keep seeing plain English plus
   * hreflang, and choosing EN in the select stops the redirect for good. */
  if (current === 'en' && stored !== 'en' && LANGS.indexOf(stored) > 0) {
    location.replace('/' + stored + '/' + page);
    return;
  }

  var select = document.getElementById('lang-select');
  if (select) {
    select.value = current;
    select.addEventListener('change', function () {
      var code = select.value;
      localStorage.setItem(LANG_KEY, code);
      location.href = (code === 'en' ? '/' : '/' + code + '/') + page;
    });
  }
  /* OS-specific download labels come from data attributes on the buttons */
  var dlPrimary = document.getElementById('dl-primary');
  var dlLabel = document.getElementById('dl-label');
  if (dlPrimary && dlLabel) {
    dlLabel.textContent = isWin ? dlPrimary.dataset.win : dlPrimary.dataset.mac;
  }
  var dlSecondary = document.getElementById('dl-secondary');
  if (dlSecondary) {
    dlSecondary.textContent = isWin ? dlSecondary.dataset.mac : dlSecondary.dataset.win;
  }
})();

/* ------------------- hero: companion extension hint -------------------- */
/* Shown only where the Chrome Web Store link makes sense: desktop
 * Chromium-family browsers (Chrome, Edge, Brave, Opera, Vivaldi). */
(function () {
  var link = document.getElementById('hero-ext');
  if (!link) return;
  var ua = navigator.userAgent || '';
  var mobile = /Android|iPhone|iPad|iPod|Mobile/i.test(ua);
  var chromiumLike = false;
  if (navigator.userAgentData && navigator.userAgentData.brands) {
    chromiumLike = navigator.userAgentData.brands.some(function (b) {
      return /chromium|chrome/i.test(b.brand);
    });
  } else {
    chromiumLike = /Chrome\/|Chromium\//.test(ua) && !/Firefox\//.test(ua);
  }
  if (chromiumLike && !mobile) {
    link.hidden = false;
    link.addEventListener('click', function () {
      phTrack('extension_click', { placement: 'hero' });
    });
  }
})();

/* ------------------------- dynamic footer year ------------------------- */
(function () {
  var y = document.getElementById('year');
  if (y) y.textContent = String(new Date().getFullYear());
})();

/* ----------------------------- sticky nav ------------------------------ */
(function () {
  var shell = document.getElementById('nav-shell');
  if (!shell) return;
  var onScroll = function () {
    shell.classList.toggle('scrolled', window.scrollY > 24);
  };
  window.addEventListener('scroll', onScroll, { passive: true });
  onScroll();
})();

/* -------------------- real download links (GitHub API) ----------------- */
(function () {
  var FALLBACK = 'https://github.com/flobro/flobro-app/releases/latest';
  var CACHE_KEY = 'flobro-dl';
  var CACHE_TTL = 60 * 60 * 1000; /* 1 hour */

  function apply(urls) {
    var mac = urls.mac || FALLBACK;
    var win = urls.win || FALLBACK;
    var primary = document.getElementById('dl-primary');
    var secondary = document.getElementById('dl-secondary');
    var navBtn = document.getElementById('nav-download');
    if (primary) primary.href = isWin ? win : mac;
    if (secondary) secondary.href = isWin ? mac : win;
    if (navBtn) navBtn.href = isWin ? win : mac;
  }

  try {
    var cached = JSON.parse(sessionStorage.getItem(CACHE_KEY) || 'null');
    if (cached && Date.now() - cached.t < CACHE_TTL) {
      apply(cached);
      return;
    }
  } catch {
    /* ignore */
  }

  fetch('https://api.github.com/repos/flobro/flobro-app/releases/latest', {
    headers: { Accept: 'application/vnd.github+json' },
  })
    .then(function (r) {
      return r.ok ? r.json() : null;
    })
    .then(function (rel) {
      if (!rel || !rel.assets) return;
      var urls = { t: Date.now() };
      rel.assets.forEach(function (a) {
        if (/\.dmg$/i.test(a.name)) urls.mac = a.browser_download_url;
        if (/(setup.*\.exe|\.exe|\.msi)$/i.test(a.name))
          urls.win = urls.win || a.browser_download_url;
      });
      sessionStorage.setItem(CACHE_KEY, JSON.stringify(urls));
      apply(urls);
    })
    .catch(function () {
      /* fallback links already in the markup */
    });
})();

/* ----------------------- hero window: player logic ---------------------- */
(function () {
  var win = document.getElementById('demo-window');
  var play = document.getElementById('demo-play');
  var progress = document.getElementById('demo-progress');
  var stage = document.getElementById('demo-stage');
  if (!win || !play || !stage) return;

  var clickTimes = [];
  var rickrolled = false; /* once per pageload is plenty */
  var staticCanvas = document.getElementById('tv-static');
  var staticCtx = staticCanvas ? staticCanvas.getContext('2d') : null;
  var staticRunning = false;

  /* --- confetti --- */
  function confettiBurst() {
    var rect = play.getBoundingClientRect();
    var stageRect = stage.getBoundingClientRect();
    for (var i = 0; i < 16; i++) {
      var c = document.createElement('span');
      c.className = 'confetti';
      var angle = (Math.PI * 2 * i) / 16 + Math.random() * 0.4;
      var dist = 90 + Math.random() * 130;
      c.style.left = rect.left - stageRect.left + rect.width / 2 + 'px';
      c.style.top = rect.top - stageRect.top + rect.height / 2 + 'px';
      c.style.setProperty('--dx', Math.cos(angle) * dist + 'px');
      c.style.setProperty('--dy', Math.sin(angle) * dist - 40 + 'px');
      c.style.setProperty('--rot', Math.random() * 540 - 270 + 'deg');
      if (i % 3 === 1) c.style.background = '#3fa9f5';
      if (i % 3 === 2) c.style.background = '#1668a8';
      stage.appendChild(c);
      setTimeout(
        function (el) {
          el.remove();
        },
        1100,
        c,
      );
    }
  }

  /* --- analog static (small canvas, ~15 fps, only while visible) --- */
  function drawStatic() {
    if (!staticRunning || !staticCtx) return;
    if (!document.hidden) {
      var img = staticCtx.createImageData(160, 100);
      var d = img.data;
      for (var i = 0; i < d.length; i += 4) {
        var v = (Math.random() * 255) | 0;
        d[i] = d[i + 1] = d[i + 2] = v;
        d[i + 3] = 255;
      }
      staticCtx.putImageData(img, 0, 0);
    }
    setTimeout(function () {
      requestAnimationFrame(drawStatic);
    }, 66);
  }
  function startStatic() {
    if (staticRunning) return;
    staticRunning = true;
    drawStatic();
  }
  function stopStatic() {
    staticRunning = false;
  }

  function resetPlayer() {
    win.classList.remove('playing', 'ended');
    stopStatic();
    /* force the progress animation to restart cleanly next time */
    if (progress) {
      progress.style.animation = 'none';
      void progress.offsetWidth;
      progress.style.animation = '';
    }
  }

  /* progress reached 100%: cue the broken TV */
  if (progress) {
    progress.addEventListener('animationend', function () {
      win.classList.add('ended');
      startStatic();
    });
  }

  /* progress pauses when the page is hidden */
  document.addEventListener('visibilitychange', function () {
    document.body.classList.toggle('vis-paused', document.hidden);
  });

  play.addEventListener('click', function () {
    var now = Date.now();
    clickTimes = clickTimes.filter(function (t) {
      return now - t < 900;
    });
    clickTimes.push(now);

    if (win.classList.contains('ended')) {
      /* pause button resets the broken TV */
      resetPlayer();
      phTrack('demo_interact', { action: 'tv-reset' });
      return;
    }

    win.classList.toggle('playing');
    win.classList.remove('wiggle');
    void win.offsetWidth;
    win.classList.add('wiggle');
    confettiBurst();
    phTrack('demo_interact', {
      action: win.classList.contains('playing') ? 'play' : 'pause',
    });

    /* triple-click within 900ms: the real thing, in a real floating window */
    if (clickTimes.length >= 3 && !rickrolled) {
      rickrolled = true;
      clickTimes = [];
      phTrack('demo_interact', { action: 'rickroll' });
      window.open(
        'https://www.youtube.com/embed/dQw4w9WgXcQ?autoplay=1',
        'flobroDemo',
        'popup,width=560,height=340,left=' +
          Math.max(0, (screen.width - 560) / 2) +
          ',top=' +
          Math.max(0, (screen.height - 340) / 3),
      );
    }
  });

  /* --- draggable by the top bar (mouse + touch via pointer events) ---
   * Once dragged, the window becomes position:fixed: it floats above the
   * whole page (below only the nav bar) and keeps its spot while scrolling.
   * The close button in the hover toolbar puts it back where it started. */
  var drag = null;

  /* The reveal entrance animation leaves a transform on the hero elements
   * (fill-mode: forwards), and a transformed ancestor would turn the
   * window's position:fixed into position:absolute. Strip the classes once
   * the entrance is done; the elements are at their final state anyway.
   * No DOM re-parenting: moving nodes restarts CSS animations and would
   * reset the progress bar. */
  document.querySelectorAll('.reveal').forEach(function (el) {
    el.addEventListener('animationend', function (e) {
      if (e.animationName === 'reveal') el.classList.remove('reveal', 'd1', 'd2');
    });
  });

  function resetWindowPosition() {
    win.classList.remove('dragged', 'dragging');
    win.style.position = '';
    win.style.left = '';
    win.style.top = '';
    win.style.right = '';
    win.style.width = '';
  }

  function startDrag(e) {
    if (e.button !== undefined && e.button !== 0) return;
    if (e.target && e.target.classList && e.target.classList.contains('x')) return;
    var winRect = win.getBoundingClientRect();
    drag = {
      dx: e.clientX - winRect.left,
      dy: e.clientY - winRect.top,
      x0: e.clientX,
      y0: e.clientY,
      moved: false,
    };
    /* freeze the current size so going fixed doesn't change it */
    win.style.width = winRect.width + 'px';
    win.classList.add('dragged', 'dragging');
    /* fixed = viewport coordinates, so the rect maps 1:1 */
    win.style.left = winRect.left + 'px';
    win.style.top = winRect.top + 'px';
    win.style.right = 'auto';
    e.currentTarget.setPointerCapture(e.pointerId);
    e.preventDefault();
  }
  function moveDrag(e) {
    if (!drag) return;
    if (Math.abs(e.clientX - drag.x0) + Math.abs(e.clientY - drag.y0) > 6) drag.moved = true;
    win.style.left = e.clientX - drag.dx + 'px';
    win.style.top = Math.max(0, e.clientY - drag.dy) + 'px';
  }
  function endDrag(e) {
    if (!drag) return;
    /* a click on the toolbar is not a drag; only count real moves */
    if (drag.moved) phTrack('demo_interact', { action: 'drag' });
    drag = null;
    win.classList.remove('dragging');
    try {
      e.currentTarget.releasePointerCapture(e.pointerId);
    } catch {
      /* ignore */
    }
  }

  var toolbar = win.querySelector('.toolbar');
  [document.getElementById('grab-strip'), toolbar].forEach(function (el) {
    if (!el) return;
    el.addEventListener('pointerdown', startDrag);
    el.addEventListener('pointermove', moveDrag);
    el.addEventListener('pointerup', endDrag);
    el.addEventListener('pointercancel', endDrag);
  });

  /* the mock close button snaps the window back home */
  var closeIcon = win.querySelector('.toolbar i.x');
  if (closeIcon) {
    closeIcon.addEventListener('pointerdown', function (e) {
      e.stopPropagation();
    });
    closeIcon.addEventListener('click', resetWindowPosition);
  }
})();

/* --------------------- demo window: use-case tabs ----------------------- */
/* The hero window cycles through the three main use cases (video,
 * pipelines, chat) so nobody mistakes Flobro for a video-only tool.
 * A manual pick stops the auto-cycle; the video easter eggs stay intact. */
(function () {
  var win = document.getElementById('demo-window');
  var tabs = document.getElementById('demo-tabs');
  if (!win || !tabs) return;
  var buttons = Array.prototype.slice.call(tabs.querySelectorAll('button'));
  var order = ['video', 'pipeline', 'chat'];
  var idx = 0;
  var timer = null;
  var TICK = 100; /* ms between progress updates */
  var CYCLE = 5000; /* ms per use case */
  var elapsed = 0;

  function setMode(mode) {
    win.classList.remove('mode-pipeline', 'mode-chat');
    if (mode !== 'video') win.classList.add('mode-' + mode);
    buttons.forEach(function (b) {
      b.classList.toggle('on', b.dataset.mode === mode);
    });
    idx = order.indexOf(mode);
    elapsed = 0;
    tabs.style.setProperty('--p', '0');
  }

  /* a manual pick stops the auto-cycle for good, fill included */
  function stopCycle() {
    if (!timer) return;
    clearInterval(timer);
    timer = null;
    tabs.classList.remove('cycling', 'paused');
    tabs.style.removeProperty('--p');
  }

  buttons.forEach(function (b) {
    b.addEventListener('click', function () {
      stopCycle();
      setMode(b.dataset.mode);
      phTrack('demo_interact', { action: 'tab', mode: b.dataset.mode });
    });
  });

  var reduced = window.matchMedia && window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  if (!reduced) {
    tabs.classList.add('cycling');
    timer = setInterval(function () {
      /* never yank the demo around mid-interaction. A pausing countdown
       * reads as broken, so fade the fill out; --p keeps its value and
       * the fill fades back in when the rotation resumes. */
      if (
        win.classList.contains('playing') ||
        win.classList.contains('ended') ||
        win.classList.contains('dragged') ||
        win.matches(':hover') ||
        document.hidden
      ) {
        tabs.classList.add('paused');
        return;
      }
      tabs.classList.remove('paused');
      elapsed += TICK;
      if (elapsed >= CYCLE) {
        setMode(order[(idx + 1) % order.length]);
      } else {
        tabs.style.setProperty('--p', String(elapsed / CYCLE));
      }
    }, TICK);
  }
})();

/* ------------------ "Entering the Matrix" easter egg -------------------- */
/* Clicking Inspect in the fake context menu does what Inspect always
 * secretly promised. Runs a few seconds, then politely leaves. */
(function () {
  var row = document.getElementById('mock-inspect');
  if (!row) return;
  var busy = false;
  row.addEventListener('click', function () {
    if (busy) return;
    busy = true;
    phTrack('demo_interact', { action: 'matrix' });
    var c = document.createElement('canvas');
    c.className = 'matrix-rain';
    document.body.appendChild(c);
    var ctx = c.getContext('2d');
    var size = 16;
    c.width = window.innerWidth;
    c.height = window.innerHeight;
    var W = c.width;
    var H = c.height;
    var cols = Math.floor(W / size);
    var drops = [];
    for (var i = 0; i < cols; i++) drops[i] = 0 - ((Math.random() * 40) | 0);
    var GLYPHS = 'アイウエオカキクケコサシスセソタチツテト0123456789FLOBRO';
    var run = true;
    function draw() {
      if (!run) return;
      ctx.fillStyle = 'rgba(0,0,0,0.08)';
      ctx.fillRect(0, 0, W, H);
      ctx.fillStyle = '#00ff6a';
      ctx.font = size + 'px monospace';
      for (var i = 0; i < cols; i++) {
        var ch = GLYPHS[(Math.random() * GLYPHS.length) | 0];
        ctx.fillText(ch, i * size, drops[i] * size);
        if (drops[i] * size > H && Math.random() > 0.975) drops[i] = 0;
        drops[i]++;
      }
      requestAnimationFrame(draw);
    }
    requestAnimationFrame(function () {
      c.classList.add('on');
    });
    draw();
    setTimeout(function () {
      c.classList.add('out');
    }, 3600);
    setTimeout(function () {
      run = false;
      c.remove();
      busy = false;
    }, 4200);
  });
})();

/* ---------------- prefetch language alternates (speculation) ------------ */
/* Makes the language switch feel instant together with the CSS
 * view-transition. Prefetch only (no prerender): cheap, and it cannot
 * fire analytics or run scripts. URLs come from the hreflang cluster. */
(function () {
  if (!HTMLScriptElement.supports || !HTMLScriptElement.supports('speculationrules')) return;
  var urls = {};
  document.querySelectorAll('link[rel="alternate"][hreflang]').forEach(function (l) {
    if (l.href && l.href !== location.href) urls[l.href] = true;
  });
  var list = Object.keys(urls);
  if (!list.length) return;
  var s = document.createElement('script');
  s.type = 'speculationrules';
  s.textContent = JSON.stringify({ prefetch: [{ source: 'list', urls: list }] });
  document.head.appendChild(s);
})();

/* ----------------------- funnel tracking helpers ----------------------- */
function phTrack(event, props) {
  if (window.posthog && window.posthog.capture) window.posthog.capture(event, props || {});
}
(function () {
  var platform = /win/i.test(
    (navigator.userAgentData && navigator.userAgentData.platform) || navigator.platform || '',
  )
    ? 'windows'
    : 'mac';
  var bind = function (id, event, props) {
    var el = document.getElementById(id);
    if (el)
      el.addEventListener('click', function () {
        phTrack(event, props);
      });
  };
  bind('dl-primary', 'download_click', { placement: 'hero', platform: platform });
  bind('dl-secondary', 'download_click', {
    placement: 'hero-secondary',
    platform: platform === 'mac' ? 'windows' : 'mac',
  });
  bind('nav-download', 'download_click', { placement: 'nav', platform: platform });
  bind('ext-store', 'extension_click', {});
  bind('sp-gh', 'donate_click', { provider: 'github-sponsors' });
  bind('sp-bmc', 'donate_click', { provider: 'buymeacoffee' });
  bind('sp-mollie', 'donate_click', { provider: 'mollie' });
})();

/* ------------------------------ Konami code ---------------------------- */
(function () {
  var seq = [
    'ArrowUp',
    'ArrowUp',
    'ArrowDown',
    'ArrowDown',
    'ArrowLeft',
    'ArrowRight',
    'ArrowLeft',
    'ArrowRight',
    'b',
    'a',
  ];
  var pos = 0;
  document.addEventListener('keydown', function (e) {
    var key = e.key.length === 1 ? e.key.toLowerCase() : e.key;
    if (key === seq[pos]) {
      pos++;
      if (pos === seq.length) {
        pos = 0;
        var body = document.body;
        if (body.classList.contains('konami')) {
          body.classList.remove('konami');
        } else {
          body.style.setProperty('--konami-hue', Math.floor(Math.random() * 360) + 'deg');
          body.classList.add('konami');
          phTrack('demo_interact', { action: 'konami' });
        }
      }
    } else {
      pos = key === seq[0] ? 1 : 0;
    }
  });
})();

/* ------------------------- analytics (PostHog) ------------------------- */
/* Cookieless: persistence in memory only, so no banners are needed.
 * Replace PH_KEY with the real project key; nothing loads until then. */
(function () {
  var PH_KEY = 'phc_tmfA5uemSD7TscmzLWQPAiqYXxfNartjfYsrjWQ6rEot';
  if (PH_KEY.indexOf('REPLACE_ME') !== -1) return;
  var s = document.createElement('script');
  s.src = 'https://s.flobro.app/static/array.js';
  s.onload = function () {
    window.posthog.init(PH_KEY, {
      api_host: 'https://s.flobro.app',
      defaults: '2026-05-30',
      persistence: 'memory',
      autocapture: false,
      capture_pageview: true,
    });
  };
  document.head.appendChild(s);
})();
