# Sponsor button configuration
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
github: cornips
buy_me_a_coffee: cornips
custom: ["https://payment-links.mollie.com/payment/uFb9QAUBabzWMqCQ4xuhq"]
