title: Flobro
tagline: Floating Browser Window
production_url: https://flobro.app
google_analytics: UA-84858849-2
theme: jekyll-theme-cayman
sass:
  sass_dir: assets/_sass
author :
  name : Flobro
  github : flobro
