title: Flobro
tagline: Floating browser window
production_url: https://flobro.app
google_analytics: G-T3C2XK0GCD
theme: jekyll-theme-cayman
sass:
  sass_dir: assets/_sass
author :
  name : Flobro
  github : flobro